package com.apollographql.apollo.interceptor

const val NETWORK_FIRST_INTERCEPTOR = 0
const val CACHE_ONLY_INTERCEPTOR = 1
const val APOLLO_PARSE_INTERCEPTOR = 2
const val NETWORK_ONLY_INTERCEPTOR = 3
const val CACHE_AND_NETWORK_INTERCEPTOR = 4
const val APOLLO_AUTO_PERSISTED_OPERATION_INTERCEPTOR = 5
const val APOLLO_CACHE_INTERCEPTOR = 6
const val CACHE_FIRST_INTERCEPTOR = 7
const val APOLLO_SERVER_INTERCEPTOR = 8
const val APOLLO_BATCHING_INTERCEPTOR = 9
